name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Start server
      run: npm start & 
      env:
        SERVER_PORT: 8080 
        
    - name: Run functionality tests
      env:
        SERVER_URL: http://localhost:8080
      run: |
        npm test 
       