Description: Notes web app EC2


Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "120.210.69.2/32"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
      VpcId:
        Fn::ImportValue: !Sub "${stackName}-network-vpc"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"
  NotesEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: !Sub ${Linux2Ami}
      KeyName: "km-jj"
      SubnetId:
        Fn::ImportValue: aaf-network-pub-sub-vpc"
      SecurityGroupIds: 
        - !Ref SecurityGroup
      Tags:
        - Key: "Name"
          Value: "NotesEC2Instance"
      UserData:
        Fn::Base64:
          ${file(deploy-script.sh)}
Outputs:
  EC2IP:
    Description: Public IP of the EC2 Instance
    Value: !GetAtt NotesEC2Instance.PublicIp