scription: Notes web app EC2

Parameters:
  # inject in the latest AMI
  Linux2Ami:
    Type: String
  # used to open up ssh port
  UserDataScript:
    Type: String
  stackName:
    Type: String

Resources:
  NotesSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "120.210.69.2/32"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
      VpcId:
        Fn::ImportValue: !Sub "${stackName}-network-vpc"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"
  NotesEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: !Sub ${Linux2Ami}
      KeyName: "aqil-standard"
      SubnetId:
        Fn::ImportValue: !Sub "${stackName}-network-pub-sub-vpc"
      SecurityGroupIds: 
        - !Ref NotesSecurityGroup
      Tags:
        - Key: "Name"
          Value: "NotesEC2Instance"
      UserData:
        Fn::Base64: !Ref UserDataScript
Outputs:
  EC2IP:
    Description: Public IP of the EC2 Instance
    Export:
      Name: !Sub "${AWS::StackName}-ip-address"
    Value: !GetAtt NotesEC2Instance.PublicIp