Description: EC2 for the notes web app

Parameters:
  # inject in the latest AMI
  Linux2Ami:
    Type: String
  # used to open up ssh port
  UserDataScript:
    Type: String
  stackName:
    Type: String
Resources:
  NotesSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP traffic"
      SecurityGroupIngress:
        - {
            IpProtocol: "tcp",
            FromPort: "22",
            ToPort: "22",
            CidrIp: "145.105.66.0/32"
          }
        - {
            IpProtocol: "tcp",
            FromPort: "80",
            ToPort: "80",
            CidrIp: "0.0.0.0/0"
          }
      VpcId: !ImportValue "${stackName}-network-vpc"
      Tags: [{
        Key: "Name",
        Value: "${AWS::StackName}-sg"
      }]
  NotesEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "${Linux2Ami}"
      KeyName: "kam-jj"
      SubnetId: !ImportValue "${stackName}-network-pub-sub-vpc"
      SecurityGroupIds: [!Ref NotesSecurityGroup]
      Tags: [{
        Key: "Name",
        Value: "NotesEC2Instance"
      }]
      UserData: !Base64 "${UserDataScript}"
