name: testing building and destorying

# defines the trigger event
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# set up the build environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # install dependencies and run tests
    - name: Install dependencies
      run: npm install
      
    - name: Start server
      run: npm start & 
      env:
        SERVER_PORT: 8080 
        
    - name: Run functionality tests
      env:
        SERVER_URL: http://localhost:8080
      run: |
        npm test.yml 

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: #need the region code

    # Deploy to AWS
    - name: Deploy to AWS
      run: # | need the aws deployment commands

    # Tear down and rebuild infrastructure
    - name: Tear down infrastructure
      run: ./teardown.sh

    - name: Rebuild infrastructure
      run: ./rebuild.sh